version: '3.4'

services:
  postgres:
    image: postgres:13.2-alpine
    restart: always
    volumes:
      - ./back/migrations/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hh
      POSTGRES_DB: hh
      POSTGRES_USER: hh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hh"]
      interval: 10s
      timeout: 5s
      retries: 5

  back:
    image: maven:3.6.3-jdk-11
    restart: always
    working_dir: /mnt/app
    command: mvn install exec:java -Dmaven.test.skip=true
    volumes:
      - gowork-back-maven-repo:/root/.m2
      - ./back:/mnt/app:Z
      - gowork-back-swagger:/mnt/app/target/api-doc
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 180s  # first start may be long due to downloading dependencies
  back-swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - gowork-back-swagger:/gowork
    environment:
      - SWAGGER_JSON=/gowork/openapi.json
    expose:
      - "8080"
    links:
      - back
    depends_on:
      - back
  back-swagger-ui-nginx:
    image: nginx
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./back/swagger-ui/nginx.conf:/etc/nginx/templates/default.conf.template
    environment:
      - BACK_NAME=back
      - BACK_PORT=8080
      - SWAGGER_UI_NAME=back-swagger-ui
      # this is internal port in virtual network
      - SWAGGER_UI_PORT=8080
    ports:
      - "8082:8082"
    links:
      - back-swagger-ui
    depends_on:
      - back-swagger-ui
  front:
    environment:
      BACK_NAME: back
      BACK_PORT: 8080
    build: ./front
    ports:
      - "3000:80"
    links:
      - back
    depends_on:
      - back
volumes:
  gowork-back-maven-repo:
  gowork-back-swagger:
